"""Validate the parser against every STL file committed under ``tests/data/``.

The ``tests/data/`` directory holds a curated corpus generated by
``tests/data/_generate.py`` covering format-detection edge cases,
ASCII line-ending variants, real-world binary-writer header
signatures, and a few small geometries. The test walks every ``.stl``
in that directory and compares the reader's output to
``vtkSTLReader`` with merging enabled.
"""

from pathlib import Path

import numpy as np
import pytest

import pyvista_stl


CORPUS_DIR = Path(__file__).resolve().parent / "data"
CORPUS_FILES = sorted(CORPUS_DIR.glob("*.stl"))

# A missing or empty corpus would make every parametrized test pass
# silently. Fail at import time so a bad checkout is obvious.
assert CORPUS_FILES, f"Empty STL corpus at {CORPUS_DIR}"


def _vtk_read(path: Path) -> tuple[np.ndarray, int, int, np.ndarray]:
    """Read an STL file with ``vtkSTLReader`` and return reference arrays.

    Returns
    -------
    sorted_points : numpy.ndarray
        Lexicographically sorted vertex coordinates.
    n_points, n_cells : int
        VTK-reported point and cell counts.
    sorted_cells : numpy.ndarray
        Each cell's three vertex coordinates sorted within the cell,
        for set-equality comparison independent of vertex ordering.
    """
    pv = pytest.importorskip("pyvista")
    from _helpers import vtk_stl_reader

    reader = vtk_stl_reader()
    reader.SetFileName(str(path))
    reader.Merging = True
    reader.Update()
    polydata = pv.wrap(reader.GetOutput())
    points = np.asarray(polydata.points, dtype=np.float32)
    if polydata.n_cells:
        cells = polydata.faces.reshape(-1, 4)[:, 1:]
        cell_vertex_sets = np.sort(points[cells], axis=1)
    else:
        cell_vertex_sets = np.empty((0, 3, 3), dtype=np.float32)
    return (
        np.sort(points, axis=0),
        polydata.n_points,
        polydata.n_cells,
        cell_vertex_sets,
    )


@pytest.mark.parametrize(
    "stl_path",
    CORPUS_FILES,
    ids=[p.name for p in CORPUS_FILES],
)
def test_corpus_matches_vtk(stl_path: Path) -> None:
    """Every committed STL in ``tests/data/`` round-trips against VTK."""
    points, indices = pyvista_stl.read(stl_path)

    assert points.dtype == np.float32
    assert indices.dtype == np.int32

    expected_points, n_points, n_cells, expected_cells = _vtk_read(stl_path)

    assert points.shape == (n_points, 3), f"point count mismatch for {stl_path.name}"
    assert indices.shape == (n_cells, 3), f"cell count mismatch for {stl_path.name}"

    if n_points:
        np.testing.assert_array_equal(np.sort(points, axis=0), expected_points)

    if n_cells:
        # Compare cells as sets of (sorted) vertices, since vertex
        # indices and within-cell vertex order are implementation
        # details.
        ours = np.sort(points[indices], axis=1)
        # Sort both arrays canonically across cells so the comparison
        # is independent of cell order.
        ours_sorted = ours[np.lexsort(ours.reshape(ours.shape[0], -1).T[::-1])]
        theirs_sorted = expected_cells[
            np.lexsort(expected_cells.reshape(expected_cells.shape[0], -1).T[::-1])
        ]
        np.testing.assert_array_equal(ours_sorted, theirs_sorted)


def test_corpus_has_expected_categories() -> None:
    """The corpus covers every documented edge case (guards against accidental deletion)."""
    names = {p.name for p in CORPUS_FILES}
    expected = {
        # Minimal cases
        "binary_zero_triangles.stl",
        "ascii_zero_triangles.stl",
        "binary_single_triangle.stl",
        "ascii_single_triangle.stl",
        # Geometry
        "binary_tetra.stl",
        "binary_cube.stl",
        "binary_sphere.stl",
        # Binary header variants
        "binary_solid_header.stl",
        "binary_with_attribute_bytes.stl",
        "binary_geomagic_header.stl",
        "binary_netfabb_header.stl",
        # ASCII line-ending variants
        "ascii_lf.stl",
        "ascii_crlf.stl",
        "ascii_cr.stl",
        # ASCII formatting variants
        "ascii_tab_indent.stl",
        "ascii_no_indent.stl",
        "ascii_scientific_floats.stl",
        # Moderate sizes
        "binary_grid_50.stl",
        "ascii_grid_30.stl",
        # Stress
        "binary_disconnected.stl",
    }
    missing = expected - names
    assert not missing, f"missing corpus files: {sorted(missing)}"
